<?php

/**
 * @file
 * Module implementation file.
 */

/**
 * Implements hook_help().
 */
function social_autopost_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  $message = NULL;
  switch ($route_name) {
    case 'social_autopost.settings':
      $message = t('Social Autopost allows social integrations so be integrated with Drupal. Every social integration is a different module that provided the API adaptors to every social network SDK.');
      break;
  }
  return $message;
}

/**
 * Implements hook_theme().
 */
function social_autopost_theme() {
  $theme = [];
  $theme['autopost'] = [
    'render element' => 'elements',
    'file' => 'autopost.page.inc',
    'template' => 'autopost',
  ];
  $theme['autopost_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'autopost.page.inc',
  ];
  return $theme;
}
